### ISSUE TITLE
Bumper fails to work on either RPi2 or Ubuntu 20.04

### ISSUE THREAD

**Issue by deltabravozulu** [bmartin5692/bumper#101]
**Describe the bug**
I have tried to get bumper set up on both a Raspberry Pi 2 and a desktop running Ubuntu 20.04. Regardless of what I do, Bumper fails to kick off correctly. I have followed the instructions both as a user account and as a sudo account. 

**To Reproduce**
1. Connect to Deebot N79S over 2.4GHz wifi and set it up to be on the network.
2. Add the following lines to a file named 02-bumper.conf on RPi2 running Pi-hole (Pi-hole static IP is 192.168.0.21, static IP of workstation is 192.168.0.20, so I changed it to 20 for running on Ubuntu) : 
```
#address=/ecouser.net/192.168.0.21
#address=/ecovacs.com/192.168.0.21
#address=/ecovacs.net/192.168.0.21
address=/ecouser.net/192.168.0.20
address=/ecovacs.com/192.168.0.20
address=/ecovacs.net/192.168.0.20
```
2. Run ```sudo service pihole-FTL reload```

3. Go to workstation. Make sure ecovacs resolves 'correctly':
```
ubuntu@ubuntu:~$ ping ecovacs.net
PING ecovacs.net (192.168.0.20) 56(84) bytes of data.
64 bytes from ubuntu.lan (192.168.0.20): icmp_seq=1 ttl=64 time=0.016 ms
64 bytes from ubuntu.lan (192.168.0.20): icmp_seq=2 ttl=64 time=0.025 ms
64 bytes from ubuntu.lan (192.168.0.20): icmp_seq=3 ttl=64 time=0.062 ms
^C
--- ecovacs.net ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 0.016/0.034/0.062/0.019 ms
```

4. Download and install bumper. 
```
ubuntu@ubuntu:~/github/testing$ git clone https://github.com/bmartin5692/bumper.git
Cloning into 'bumper'...
POST git-upload-pack (265 bytes)
remote: Enumerating objects: 195, done.
remote: Counting objects: 100% (195/195), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 1384 (delta 125), reused 147 (delta 90), pack-reused 1189
Receiving objects: 100% (1384/1384), 25.21 MiB | 19.28 MiB/s, done.
Resolving deltas: 100% (838/838), done.

ubuntu@ubuntu:~/github/testing$ cd bumper
ubuntu@ubuntu:~/github/testing/bumper$ pipenv install

ubuntu@ubuntu:~/github/testing/bumper$ pipenv install
Creating a virtualenv for this project…
Using /usr/bin/python3 (3.8.2) to create virtualenv…
⠋created virtual environment CPython3.8.2.final.0-64 in 255ms
  creator CPython3Posix(dest=/home/ubuntu/.local/share/virtualenvs/bumper-2idgPeZ8, clear=False, global=False)
  seeder FromAppData(download=False, msgpack=latest, distro=latest, six=latest, pep517=latest, html5lib=latest, requests=latest, retrying=latest, certifi=latest, colorama=latest, chardet=latest, distlib=latest, pytoml=latest, pyparsing=latest, packaging=latest, pip=latest, setuptools=latest, wheel=latest, ipaddr=latest, idna=latest, appdirs=latest, contextlib2=latest, progress=latest, pkg_resources=latest, urllib3=latest, webencodings=latest, lockfile=latest, CacheControl=latest, via=copy, app_data_dir=/home/ubuntu/.local/share/virtualenv/seed-app-data/v1.0.1.debian)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Virtualenv location: /home/ubuntu/.local/share/virtualenvs/bumper-2idgPeZ8
Installing dependencies from Pipfile.lock (2ba937)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 19/19 — 00:00:06
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

5. Try to use bumper:
```
ubuntu@ubuntu:~/github/testing/bumper$ pipenv run python -m bumper
Creating certificates
-------- Create_Certs --------
-------- Starting Certificate Creation --------
Options: 
 Output Directory: /home/ubuntu/github/testing/bumper/certs
 Input SAN List: /home/ubuntu/github/testing/bumper/create_certs/Bumper_SAN.txt
-------- Creating CA Cert --------
2020/07/30 17:57:43 ca.crt created at /home/ubuntu/github/testing/bumper/certs/ca.crt
2020/07/30 17:57:43 ca.key created at /home/ubuntu/github/testing/bumper/certs/ca.key
-------- Creating Server Cert --------
2020/07/30 17:57:43 bumper.crt created at /home/ubuntu/github/testing/bumper/certs/bumper.crt
2020/07/30 17:57:43 bumper.key created at /home/ubuntu/github/testing/bumper/certs/bumper.key
-------- Certificate Creation Complete --------
Certificates created
[2020-07-30 17:57:44,015] :: INFO :: bumper :: Starting Bumper
[2020-07-30 17:57:44,026] :: INFO :: mqttserver :: Starting MQTT Server at 127.0.1.1:8883
[2020-07-30 17:57:44,028] :: INFO :: xmppserver :: Starting XMPP Server at 127.0.1.1:5223
[2020-07-30 17:57:44,029] :: WARNING :: hbmqtt.client :: MQTT connection failed: ConnectionRefusedError(111, "Connect call failed ('127.0.1.1', 8883)")
[2020-07-30 17:57:44,029] :: WARNING :: hbmqtt.client :: Connection failed: ConnectException(ConnectionRefusedError(111, "Connect call failed ('127.0.1.1', 8883)"))
[2020-07-30 17:57:44,029] :: INFO :: hbmqtt.broker :: Listener 'tls1' bind to 127.0.1.1:8883 (max_connections=-1)
[2020-07-30 17:57:45,041] :: INFO :: hbmqtt.broker :: Listener 'tls1': 1 connections acquired
[2020-07-30 17:57:45,042] :: INFO :: hbmqtt.broker :: Connection from 127.0.0.1:38390 on listener 'tls1'
[2020-07-30 17:57:45,044] :: INFO :: mqttserver :: Bumper Authentication Success - Helperbot: helperbot@bumper/helperbot
```

_Then it just sits there. Nothing happens._ 

Removing the virtualenv and the bumper dir, redownloading, and doing everything again as the superuser results in the exact same behavior. The precise outcome occurs regardless of whether or not I am on the RPi or my desktop, point by point. 
 

**Expected behavior**
It works. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspbian and Ubuntu 20.04

**Smartphone (please complete the following information):**
 - Device:Nexus 5 running Android 9 (LineageOS) and Pixel 2 XL running Android 10 (rooted)

**Vacuum (please complete the following information):**
 - Model: Deebot N79S

**Comment by deltabravozulu** [comment]
As another point, [the docs](https://bumper.readthedocs.io/en/latest/Use_With_App/#import-the-bumper-ca-cert) suggest there should be a vile called ./certs/CA/cacert.crt but the only thing in my bumper certs folder are as follows (note that they are listed as owned by root:root because this was after my run as a superuser:
```
ubuntu@ubuntu:~/github/testing/bumper/certs$ ls -lah
total 32K
drwxrwxr-x  3 ubuntu  ubuntu  4.0K Jul 30 18:44 .
drwxrwxr-x 12 ubuntu  ubuntu  4.0K Jul 30 18:31 ..
-rw-r--r--  1 root root 1.5K Jul 30 18:32 bumper.crt
-rw-------  1 root root 1.7K Jul 30 18:32 bumper.key
-rw-r--r--  1 root root 1.2K Jul 30 18:32 ca.crt
-rw-------  1 root root 1.7K Jul 30 18:32 ca.key
-rw-rw-r--  1 ubuntu  ubuntu    62 Jul 30 18:31 README.md
drwxrwxr-x  2 ubuntu  ubuntu  4.0K Jul 30 18:41 .stfolder
-rw-------  1 ubuntu  ubuntu     0 Jul 30 18:44 .stignore
```

**Comment by deltabravozulu** [comment]
To further add color to this, even after importing the cert through root on Android 9 and 10 (I forced the generated ca.crt file with no changes to be accepted as a system certificate which has worked well for things like mitmproxy and other similar apps) and it will not let me use the app (possibly due to the DNS redirect with no server running?)

**Comment by deltabravozulu** [comment]
Well, I am a fool. This indeed works without using sudo if one merely does:
```pipenv run python -m bumper --listen <ip address of host> --announce <ip address of host>```

I have it running without sudo on my Pi. Bot shows up on http://192.168.0.21:8007

**Comment by deltabravozulu** [comment]
Now, with that said, neither the old Ecovacs nor the new Ecovacs Home apps work on Android when being served from my Pi. The old Ecovacs app _definitely_ worked when I ran the python module from my desktop and shipped the cert to my phone.

**Comment by deltabravozulu** [comment]
I forgot that the .bashrc on my ubuntu desktop basically forces root and $USER to share the same PATH among other env variables when conducting user operations. As such, what I experienced was me installing bumper as a user and running bumper as root. 

With that said, I was able to connect to it via the app using a cert generated by my ubuntu computer while using a fresh installation on my pihole. @bmartin5692 This seems...odd. The cert should be server specific but seems to function universally. 

I'll post one more update that is specific to what I did to make everything work in case anyone else runs into this and then I'll close this bug.

**Comment by deltabravozulu** [comment]
If a person has a machine running Ubuntu 20.04 or a RPi running Raspbian Buster (Debian 10) and uses and Android devices that is running Android > 7 with a Deebot N79S, the following may work for you:

0) _optional:_ Log into the Android app and make sure your device connects over 2.4GHz WiFi. Follow the device specific instructions from Ecovacs. 

1) Set a static IP for the server/workstation/RPi/whatever that you will be hosting your bumper server on in your DHCP server (usually your router, but will be your Pi-hole if you set the pihole up as your DHCP server, of course. Mine isn't, but a lot of people do it that way) 
**Note: IP of my server is 192.168.0.21. Yours will likely be something else.**

2) Create a custom dnsmasq configuration file: 
```sudo nano /etc/dnsmasq.d/02-bumper.conf```

3) Add these lines to it:  
`address=/ecouser.net/192.168.0.21`
`address=/ecovacs.net/192.168.0.21`
`address=/ecovacs.com/192.168.0.21`
and then write output (ctrl+o) --> save filename  (enter) --> exit (ctrl+x)

4) Reload the pihole-FTL service, if [using a Pi-hole ](https://bumper.readthedocs.io/en/latest/DNS_Setup/) (otherwise, probably reboot whatever thingy you are modding dnsmasq on):
```sudo service pihole-FTL reload```

5) Download the good stuff to the future bumper server:
`git clone https://github.com/bmartin5692/bumper.git`

6) Move into that directory:
`cd bumper`

7) Get that puppy installed to a virtualenv (you may need to run `sudo apt install pipenv -y` if it isn't installed):
`sudo pipenv install`

8) Git 'r done (specifying 'listen' and 'announce' addresses helped me immensely): 
`sudo pipenv run python -m bumper --listen 192.168.0.21 --announce 192.168.0.21`

9) Power off your robotic vacuum cleaner. You may need to pull the battery. Might need some screwdrivers. I didn't bother pulling the battery, since it worked as soon as I turned it back on. YMMV. 

10) You'll see that some certs have been birthed. We'll need to find a fancy way to get those to your phone. If your phone isn't rooted, I'm not sure this will work for you, so if my ideas fail, go for [Bumper's official documentation](https://bumper.readthedocs.io/en/latest/Use_With_App/#importing-the-ca-cert-on-android) (they might not work for you either! I don't know. I've never had a non-rooted phone): 
Open a new terminal or file manager or something, leaving the old terminal running. FInd some way to get the ca.crt file from ./bumper/certs/ to your phone. I don't care if you use [syncthing](https://syncthing.net/), adb, email, telegram, rewriting the cert by hand, copypasta over MTP, etc. Just get it on the phone. 

11) If your Andy Rubin phone is rooted, and happens to have [Magisk](https://github.com/topjohnwu/Magisk), go on there and scoop up [Move Certificates](https://github.com/Magisk-Modules-Repo/movecert). To double down on this cert control, if you are rocking an even more fun situation and have [EdXposed](https://github.com/ElderDrivers/EdXposed) ([Xposed](https://github.com/rovo89/Xposed) is fine too if you're able to get it to work...) , go to Download and treat yourself to [TrustMeAlready](https://github.com/ViRb3/TrustMeAlready). This should bypass the need of all the hard work outlined on the [official documentation](https://bumper.readthedocs.io/en/latest/Use_With_App/#importing-the-ca-cert-on-android) (although I did try it and it did seem to work). 

12) Click the ca.crt file from Android file manger. Install it as a user cert. Now reboot. Ideally, if the Magisk or EdXposed modules are installed, you should be good to go re: certs. 

13) Open the app. You will note that the Ecovacs Home app might not work. I think it may use certificate pinning. I've bypassed that on one device, but you won't need to if you install [version 1.4.6](https://www.apkmirror.com/apk/ecovacs-robotcs/ecovacs/ecovacs-1-4-6-release/ecovacs-1-4-6-android-apk-download/download/) of old Ecovacs.

14) Open the app. It should finally work for ya :^) 

15) _optional_: block everything related to ecovacs public IPs in your router because damn, they like to try to talk to ya. 

_todo: figure out how to run [bumper on startup](https://github.com/bmartin5692/bumper/issues/98#issuecomment-643788229) and how to use [sucks](https://bumper.readthedocs.io/en/latest/Use_With_Sucks/) since I know I'll have a basket of problems along the way._

**Comment by ErfolgreichCharismatisch** [comment]
Hi, can you help me with https://github.com/bmartin5692/bumper/issues/125 ?

**Comment by deltabravozulu** [comment]
@ErfolgreichCharismatisch  I checked #125. I have spent about 20 minutes trying to get it to work on a RPi4 with a random stock phone (unrooted) I had lying around but I think the primary problem here is packet routing. We need some kind of "internet", even if it's just an intranet₁. I am not sure that 127.0.0.1 would work in this case-- you probably need a separate VLAN for IoT things to get this set of scripts to work 'offline'. 


1. Intranet--for anyone who reads this--I just mean an internet inside your house that is specifically only meant to let devices in your house talk to each other as opposed to connecting to the real internet. To move things between computers  (including the computer in your phone or in your robot vacuum or magic toilet lightup bidet or whatever) that aren't functioning as basic receivers/transmitters like your car radio, you need something to sort the messages being sent, which is done at a base level by your internet router

**Comment by hht355** [comment]
Hello @deltabravozulu,

I'm having trouble getting the app to work with bumper.
Currently I can see from the web, the app can somehow start connection to bumper but failed
[https://gitter.ems.host/_matrix/media/r0/download/gitter.im/90528b5d4008e0d70b30f40cb7cb4fe435eb6368](url)

I see your comment below:
"_Open the app. You will note that the Ecovacs Home app might not work. I think it may use certificate pinning. I've bypassed that on one device, but you won't need to if you install of old Ecovacs._"

Here are some debug log:
docker-compose-bumper-1  | {"request": {"route_name": "portal_api_appsvr_app", "method": "POST", "path": "/api/appsvr/app.do", "query_string": "", "raw_path": "/api/appsvr/app.do", "raw_headers": "(b'Host', b'portal.ecouser.net'),(b'Content-Type', b'application/json'),(b'Connection', b'keep-alive'),(b'Accept', b'*/*'),(b'User-Agent', b'EcovacsHome/2.4.0 (iPhone; iOS 16.4.1; Scale/3.00)'),(b'Accept-Language', b'en-GB;q=1, ja-GB;q=0.9, vi-GB;q=0.8, th-GB;q=0.7'),(b'Content-Length', b'40'),(b'Accept-Encoding', b'gzip, deflate, br')", "body": "{'todo': 'GetCodepush', 'version': '2.4.0'}"}, "response": {"status": "200", "body": "{'result': 'fail', 'todo': 'result'}"}}

I'm quite stuck here.
Can you help me with that? Thank you a lot.

**Comment by hoangtran355** [comment]
hello @deltabravozulu 

I'm trying to get the bumper works with the app. It looks like the bot and the app (client) can connect to bumper, but from the app UI it shows "data submission" error.

I tried to turn on debug mode and it looks like the app is connected but fail to send command

_docker-compose-bumper-1 | [2023-05-18 14:14:26,092] :: DEBUG :: hbmqtt.client.plugins.packet_logger_plugin :: logging :: on_mqtt_packet_received :: 34 :: helperbot@bumper/helperbot <-in-- PingRespPacket(ts=2023-05-18 14:14:26.083820, fixed=MQTTFixedHeader(length=0, flags=0x0), variable=None, payload=None)
docker-compose-bumper-1 | {"request": {"route_name": "portal_api_appsvr_app", "method": "POST", "path": "/api/appsvr/[app.do](http://app.do/)", "query_string": "", "raw_path": "/api/appsvr/[app.do](http://app.do/)", "raw_headers": "(b'Host', b'[portal.ecouser.net](http://portal.ecouser.net/)'),(b'Content-Type', b'application/json'),(b'Connection', b'keep-alive'),(b'Accept', b'/'),(b'User-Agent', b'EcovacsHome/2.4.0 (iPhone; iOS 16.4.1; Scale/3.00)'),(b'Accept-Language', b'en-GB;q=1, ja-GB;q=0.9, vi-GB;q=0.8, th-GB;q=0.7'),(b'Content-Length', b'40'),(b'Accept-Encoding', b'gzip, deflate, br')", "body": "{'todo': 'GetCodepush', 'version': '2.4.0'}"}, "response": {"status": "200", "body": "{'result': 'fail', 'todo': 'result'}"}}_

Could you please help a little here? Thank you a lot.
