### ISSUE TITLE
Ecovacs Home App not working on IOS since Version 2.0.0 

### ISSUE THREAD

**Issue by slev1n** [bmartin5692/bumper#114]
**Describe the bug**
Ecovacs Home App not working on IOS since Version 2.0.0.
Error on data transmission (api not found 404)

**To Reproduce**
Open the App

**Expected behavior**
App is working

**Screenshots**
<img width="551" alt="PNG-Bild" src="https://user-images.githubusercontent.com/8486977/112716200-369f5a00-8ee5-11eb-9ab8-b020a963437d.png">
.

**Desktop (please complete the following information):**
 - IOS and IPadOS

**Smartphone (please complete the following information):**
 - Device: iphone X and Ipad Mini
 - OS: 14.4.1

**Vacuum (please complete the following information):**
 - Model:  Deebot 901

**Comment by aderzapf** [comment]
I have the same issue. Any advice what’s required to fix the issue?

**Comment by d4rkd3v1l** [comment]
Same here.

iPhone 12 Pro
iOS 14.5 public beta 5.
Deebot 950

Also pretty sure it broke with the 2.0.0 Ecovacs App update. Probably breaking API changes?

![IMG_2C553E3AF082-1](https://user-images.githubusercontent.com/13336238/113111248-492cd280-9208-11eb-8727-232a92bdd8c1.jpeg)

**Comment by edenhaus** [comment]
The app uses new endpoints, which does not yet exist in bumper. Therefore bumper will return the status code 404 (not found).

Hopefully I have time next week and can add some of them.

**Comment by schwatter** [comment]
@edenhaus 

Bumper is running. I also get fhem connected to bumper with mqtt. I tried to connect now the app with bumper, but no luck.
I copied your new plugins in the bumper/plugins folder. Restartet bumper. I tested with cert on Android 5 and 10.
I always get in the App first error (101,-9001) and then next (204,-9001) .

Pihole is running wit dnsmasq.

```
address=/ecouser.net/192.168.178.6
address=/ecovacs.com/192.168.178.6
address=/ecovacs.net/192.168.178.6
address=/puplic.itls.eu-central-1.aliyuncs.com/192.168.178.6
address=/portal-ww.ecouser.net/192.168.178.6
address=/mq-ww.ecouser.net/192.168.178.6
address=/api-app.dc-eu.ww.ecouser.net/192.168.178.6
address=/users-base.dc-eu.ww.ecouser.net/192.168.178.6
address=/jmq-ngiot-eu.dc.ww.ecouser.net/192.168.178.6
address=/lbo.ecouser.net/192.168.178.6
address=/api-app.dc-eu.ww.ecouser.net/192.168.178.6
address=/msg-eu.ecouser.net:5223/192.168.178.6
address=/jmq-ngiot-eu.area.ww.ecouser.net/192.168.178.6
address=/api-rop.dc-eu.ww.ecouser.net/192.168.178.6
```

Any advise?

cheers schwatter

**Comment by edenhaus** [comment]
> @edenhaus
> 
> Bumper is running. I also get fhem connected to bumper with mqtt. I tried to connect now the app with bumper, but no luck.
> I copied your new plugins in the bumper/plugins folder. Restartet bumper. I tested with cert on Android 5 and 10.
> I always get in the App first error (101,-9001) and then next (204,-9001) .
> 
> Pihole is running wit dnsmasq.
> 
> ```
> address=/ecouser.net/192.168.178.6
> address=/ecovacs.com/192.168.178.6
> address=/ecovacs.net/192.168.178.6
> address=/puplic.itls.eu-central-1.aliyuncs.com/192.168.178.6
> address=/portal-ww.ecouser.net/192.168.178.6
> address=/mq-ww.ecouser.net/192.168.178.6
> address=/api-app.dc-eu.ww.ecouser.net/192.168.178.6
> address=/users-base.dc-eu.ww.ecouser.net/192.168.178.6
> address=/jmq-ngiot-eu.dc.ww.ecouser.net/192.168.178.6
> address=/lbo.ecouser.net/192.168.178.6
> address=/api-app.dc-eu.ww.ecouser.net/192.168.178.6
> address=/msg-eu.ecouser.net:5223/192.168.178.6
> address=/jmq-ngiot-eu.area.ww.ecouser.net/192.168.178.6
> address=/api-rop.dc-eu.ww.ecouser.net/192.168.178.6
> ```
> 
> Any advise?
> 
> edit:
> On Android HttpCanary is running. So Https sniffing is not a problem. If you need something, guide me.
> 
> cheers schwatter

Please comment next time directly on the PR and as written in the description of the PR: „This PR is work in progress and currently not all endpoints are implemented. Feel free to test it and also to add some of the missing ones.“

I haven‘t implemented yet all endpoints. Currently all endpoints for the new auth are missing... Ecovacs uses since v2 oauth.
Analysing each request the app makes is time consuming and therefore I have open the PR as draft so others can help me. Please feel free to analyse the requests yourself. I‘m planning only to analyse the ios app. I don‘t think the android one will make different calls but you never know.
