### ISSUE TITLE
[Question] Working Ecovacs Home / Android Version

### ISSUE THREAD

**Issue by alecdotninja** [bmartin5692/bumper#115]
Hello! :wave:

I'm trying to get the Ecovacs Home app working Bumper, but I keep running into "Data submission" errors (screenshots below). I've tried a few different versions (1.3, 1.5, and 1.6) on Android 9. Is someone with a working setup willing to share what version of the Ecovacs Home app and Android they are running?

Thank you!

![Screenshot from 2021-04-06 16-46-05](https://user-images.githubusercontent.com/4643450/113792388-afc75a00-96fa-11eb-9275-46dd9ef40f09.png)
![Screenshot from 2021-04-06 16-59-42](https://user-images.githubusercontent.com/4643450/113792400-b524a480-96fa-11eb-876a-f0f883953654.png)

**Comment by edenhaus** [comment]
Have you imported the certs as specified in the docs?
https://bumper.readthedocs.io/en/latest/Use_With_App/

**Comment by puddly** [comment]
I've run 1.1.7 and 1.6.3 on Android 11 without any major issues. I believe you have to "set up" the app to get to the login screen, after which bumper will work.

**Comment by alecdotninja** [comment]
@edenhaus Yes, and I do see that certificate loaded in the system section:

![Screenshot from 2021-04-19 01-40-59](https://user-images.githubusercontent.com/4643450/115207391-68ed4300-a0b0-11eb-81c6-fce1ca01b090.png)

@puddly Thank you for the confirmation! I'll try building a new emulator with those versions and see if I can get it working.

In the meantime, I'm going to close this.
