### ISSUE TITLE
Create docker container

### ISSUE THREAD

**Issue by scottyphillips** [bmartin5692/bumper#26]
Hi, I am volunteering to assist with testing as I have recently purchased a D600 and am successfully using your fork of the sucks library in Home Assistant at present. I’ll download the server on the weekend and have a play. 

Also, jumping the gun a little here (lol) but may I suggest that you add support for running your app in a Docker container? Again would be happy to help there as well.

This looks like a cool project as I am not a fan of cloud based APIs for all my IOT devices and outside of the Deebot I have managed to avoid all of them..

**Comment by bmartin5692** [comment]
@scottyphillips - Thanks for volunteering and the interest.  I expect your D600 will work great with bumper (it uses the same protocols as the D900).

There is a lot of work to be done, my current working branch is dev_broken-XMPP.  I've been working to move everything to asyncio, but need to fix XMPP (used by other bots like N79/Ozmo).

I expect to make it work in docker will take some modifications.  I think that should wait until master is stable on a 1.0 (post the asyncio fixes and it works with other bots again).

I'm going to update this issue to "Create docker container" for tracking.  Let me know how your testing goes with bumper.
