### ISSUE TITLE
XMPP Not Functioning with N79S

### ISSUE THREAD

**Issue by zombielinux** [bmartin5692/bumper#38]
**Describe the bug**
No traffic visible on console output using either documentation in README or "python start_bumper.py" when attempting to connect Deebot N79S

**To Reproduce**
1. Set up Bumper using QuickStart guide
2. Set up DNS forwards in pfsense
3. Connect Deebot to network

**Expected behavior**
We expected to see output from the console, however nothing beyond the startup messages were printed. 

**Desktop (please complete the following information):**
 - OS: Archlinux inside LXC container, kernel 4.15.18

**Smartphone (please complete the following information):**
 - Device: Nexus 4
 - OS: Android 5.1.1

**Vacuum (please complete the following information):**
 - Model: Deebot N79S

**Comment by bmartin5692** [comment]
Hi @zombielinux -
Can you try running with debug?

`pipenv run python start_bumper.py --debug`

**Comment by zombielinux** [comment]
I get the same result with that. No response at all

**Comment by DENightOne** [comment]
Sounds like your local DNS is not working.... when you point your app and Deebot at bumper with debug on the console goes crazy with logs

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by zombielinux** [comment]
@DENightOne I'm not sure about that. If i ping any of the domains, they resolve to the correct IP.

**Comment by DENightOne** [comment]
I forgot to ask if you are running on a windows system....if so then it is windows firewall that is stopping the traffic...to test you can turn off the windows firewall to test....if it starts working then you can add rules to the advanced firewall so that you PC remains secure.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by zombielinux** [comment]
Nope. Running on an LXC Archlinux container sitting on top of proxmox/debian.

**Comment by DENightOne** [comment]
Ok....exactly same as me....I also had a problem as the code binds to the “localhost loopback” when starting..... I start with the following command

pipenv run python start_bumper.py --debug –-listen 192.168.1.20  (IP address of your VM)  when I don’t add the listen I cant access my vm, it might be a proxmox thing.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bmartin5692** [comment]
I’m surprised you don’t see anything in the logs with debug enabled.  You should have something in the logs folder to review. 

I’ve got a very large PR and update coming soon from the create_certs branch that makes a number of changes.  It is lacking documentation for setup/usage currently, but you could try that branch if you have time and see how it does. The biggest change is requiring the user to generate their own certs, but you could steal the ones from the tests directory and put them in the certs folder.

**Comment by zombielinux** [comment]
the --listen argument got the phone app to talk to it, but i havn't been able to get the vacuum up and running on it yet. might have to delete those dns redirects and try again.

**Comment by DENightOne** [comment]
On some vacuums you have to take the battery out to power cycle the robot....on the 900 and 901 you only have to turn the vacuum off and on for it to do a new DNS query.......thats all I can think of to get the vacuum to clear its DNS cache

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bmartin5692** [comment]
I’ve pulled a large update into master.  A number of things have changed including how to start bumper and where data is stored etc. I believe all of the docs have been updated regarding this. 

Let me know if this helps you, and definitely try the listen option @DENightOne mentions.

**Comment by zombielinux** [comment]
Alright. I've had a chance to fiddle with it again. I've got the N79S connected, i think. The wifi LED is still blinking and the server log never says anything beyond 
```
[2019-06-11 21:50:24,090] :: INFO :: confserver :: Announcing EcoMsgNew Server to bot as: 127.0.1.1:5223
[2019-06-11 21:50:24,093] :: INFO :: confserver :: Announcing EcoUpdate Server to bot as: 47.88.66.164:8005
```

I've also done a packet trace on it starting up and it queries 47.88.66.164, which resolves to users-na.ecousers.net. DNS forwarding that doesn't change as that seems to be hardcoded in somewhere. 

I did some packet tracing and found its reaching out to that address for the latest firmware at the path of https://users-na.ecousers.net/products/wukong/class/155/firmware/latest.json

**Comment by bmartin5692** [comment]
That’s perfect. Try adding the “--announce” option and specifying the IP of your server. What’s happening is the bot connects and is told to connect to the XMPP server at 127.0.1.1, which isn’t really valid.

**Comment by bmartin5692** [comment]
@zombielinux - Did the --announce option work for this? I want to close this out.

**Comment by zombielinux** [comment]
No. I wasn't able to get the robot to be controlled through it. I'm not sure what the issue is at this point. 

Additionally, I couldn't get the app to connect either. Its been on my to-do list to dive in and troubleshoot some more.

**Comment by zombielinux** [comment]
Alright. I think i've got it connected, but not sure why my sucks client isn't connecting, and after the toddler hit the "log out" function on the app, I can't log back in. 

I'll create a new ticket for that though.
