### ISSUE TITLE
Investigate Androind 9 (Pie) and Certificate Pinning

### ISSUE THREAD

**Issue by bmartin5692** [bmartin5692/bumper#43]
@DENightOne reports the app doesn't work on Android 9 (Pie) possibly due to certificate pinning.

TODO: Setup Android Studio/Emulator and test. 

This article may be worth reviewing:
[Four Ways to Bypass Android SSL Verification and Certificate Pinning](https://blog.netspi.com/four-ways-bypass-android-ssl-verification-certificate-pinning/)

**Comment by bmartin5692** [comment]
@DENightOne - I haven't had the time to dig into this yet, however I made some changes to allow for the app to work on iOS13 which introduced some new certificate restrictions.  

The changes were added in https://github.com/bmartin5692/bumper/commit/e873e22fd35cecf66fa178e897e950bb47e12c9d and conform to the requirements from apple at https://support.apple.com/en-us/HT210176 

If you are still using Bumper could you try the [Ozmo950 branch](https://github.com/bmartin5692/bumper/tree/ozmo950) , generate new certificates, and see if it works for Android 9 as well?

**Comment by DENightOne** [comment]
Will do

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
