### ISSUE TITLE
Features supported?

### ISSUE THREAD

**Issue by uchagani** [bmartin5692/bumper#48]
First of all, thank you for keeping this project alive.

Do all of the features from the Ecovacs app work with bumper?  For example, zone-cleaning, no-go lines, etc.

**Comment by bmartin5692** [comment]
Hi @uchagani -
Yes, all features work.  Bumper acts as a replacement for the central server of EcoVacs, which just facilitates the app talking with the robots.  Almost all of the features are driven by the robot / app itself and not tied to the central server.

**Comment by uchagani** [comment]
Fantastic. I'd love to help out on the project both this and your sucks fork (as that seems to be the most up to date version). Are there development docs I can comb through?

**Comment by bmartin5692** [comment]
Not really.  I haven't had the time to really document, but try to have tests for all which somewhat explains.  For how Bumper works the ["How it works" doc](https://github.com/bmartin5692/bumper/blob/master/docs/How_It_Works.md) may be the best.  You really are looking at Web/API (confserver), MQTT and XMPP (depending on bot).  The bots really handle most of the logic, with Bumper just relaying messages between the client and bot.  

The Sucks project has more documentation on [the protocol / commands](https://github.com/bmartin5692/sucks/blob/master/protocol.md), but all of it varies based on the model.
