### ISSUE TITLE
Logged out, can't log back in

### ISSUE THREAD

**Issue by zombielinux** [bmartin5692/bumper#55]
**Describe the bug**
After a toddler hits the log-out button, I cannot log in. 

**To Reproduce**
1. Hand phone to toddler
2. Gaze upon the "login" screen
3. Attempt to log in with usual username/password
4. See Log

**Expected behavior**
Login with view of robot

**Actual Behavior**
```[2019-10-14 16:51:35,487] :: INFO :: confserver :: client with devid $HASH attempting login```
```[2019-10-14 16:51:38,566] :: ERROR :: confserver :: 'did'```
```Traceback (most recent call last):```
  ```File "/root/bumper/bumper/confserver.py", line 492, in _auth_any```
```    bumper.user_add_bot(tmpuser["userid"], bot["did"])```
```KeyError: 'did'```

**Desktop (please complete the following information):**
 - OS: [e.g. Linux/Mac/Windows]

**Smartphone (please complete the following information):**
 - Device: Nexus Ancient
 - OS: Android 5.1.1

**Vacuum (please complete the following information):**
 - Model: Deebot N79

**Extra Info** 

Sucks cannot log in using any username/password combination.

**Comment by bmartin5692** [comment]
@zombielinux - Thanks for the laugh, I've been there with toddler bugs.

I wasn't quite able to reproduce this, and actually think your database may be corrupt.  I think the best thing is to delete the bumper.db in your data directory then try again.  I went ahead and put in a test and some better handling if a bot happens to end up in the database without a DID attribute. Hopefully that will catch and fail gracefully if this happens in the future.  This change has been merged into the master, if you want to pull and try again.
