### ISSUE TITLE
Error when running with Docker - Container does not start

### ISSUE THREAD

**Issue by mbaehr2909** [bmartin5692/bumper#73]
Hi there,

When running Sucks with Docker, the Container does not seem to start.
It gives the Error exec user process caused "exec format error".

OS: Raspbian 10
System: Raspberry Pi 4 B

I cannot get the Container to start, when running the Command stated in your Readme.

Greetings,
Max

**Comment by bmartin5692** [comment]
It's currently building for linux/amd64 only on Dockerhub.  I need to look into multiarch and having it build for arm as well.

**Comment by bmartin5692** [comment]
I went through the following docs (https://docs.docker.com/docker-for-mac/multi-arch/).  The latest build should now be available from Pis if you try to pull again.

ToDo: Make this happen via CI

**Comment by mbaehr2909** [comment]
Thanks very much!
Now it‘s working!

Now I just have to see why the Sucks Command doesn’t work...

**Comment by ErfolgreichCharismatisch** [comment]
Hi, can you help me with https://github.com/bmartin5692/bumper/issues/125 ?
