### ISSUE TITLE
Crash on "Creating certificates" when running docker on arm64/aarch64

### ISSUE THREAD

**Issue by joe540** [bmartin5692/bumper#81]
**Describe the bug**
Hi,   I'm trying to run your docker container on a arm64/aarch64 computer and, when starting, it does output "Creating certificates", but then the docker container die just after.

I tried running it on my pc (amd64) and it seems to be ok

**To Reproduce**
1. docker pull bmartin5692/bumper
2. docker run -it -e "BUMPER_ANNOUNCE_IP=192.168.0.198" -p 443:443 -p 8007:8007 -p 888
3:8883 -p 5223:5223 --name bumper2 bmartin5692/bumper

**Expected behavior**
after "Creating Certificates", the container should generate them and continue running

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Additional context**

**Comment by bmartin5692** [comment]
Hi @joe540 -
This should be fixed. 

I've tested this on a Pine64, and it worked properly.

**Comment by joe540** [comment]
Thanks a lot for your super fast fix. That seems to work for me also! (I'm running it as a Home Assistant hassi.io addon)
